### ISSUE TITLE
Attack is known and mitigated

### ISSUE THREAD

**Issue by shellster** [OWASP/QRLJacking#1]
Unless I'm missing something the SQRL documentation specifically mentions this type of attack and mitigates it in a proper implementation: https://www.grc.com/sqrl/phishing.htm

**Comment by SymbianSyMoh** [comment]
Hi @shellster, Sorry for our delayed reply, Yes for sure the attack is not that very new and there's some sources just walked around it but we went in a detailed way!

Also How you see in a summarized way that SQRL mitigates such attack?

**Comment by shellster** [comment]
The SQRL spec mitigates this attack by requiring the the SQRL client to reply only to the host from which the challenge originated.  Origination is determined by the the QR code, and is HMAC'd to prevent tampering.  Therefore, if your MITM website steals a valid QR code from Site A, when the client reads the QR code, it will see it is for Site A.  The client won't respond to your website, it will respond directly to the legitimate website.

Now your attack is correct that it can keep checking the validity of the session, and in theory, perform a session hijack.  However, the SQRL protocol specifically states (in the section I link) that for highly sensitive applications, you should require the SQRL authenticating agent to perform each sensitive action, which would bypass any session hijacking MITM attack you mentioned, because the client would only respond to authentic URL's which are provided via the HMAC'd challenge.  Also, using standard secure programming practices, any serious account functionality should require re-authentication.  So in this case the attack is certainly no worse than a typical man-in-the-middle attack against a password and username, in fact, it is far less serious, even in the worst case, because the attack is a single-session hijack.
