### ISSUE TITLE
Error run with python 3.8.3rc1

### ISSUE THREAD

**Issue by Dazmed707** [OWASP/QRLJacking#100]
error run program in Parrot 4.9.1 x64
![image](https://user-images.githubusercontent.com/35184132/82770544-76f6fd00-9e28-11ea-8a47-01fde3a1c6df.png)

**Comment by DarkShade94649** [comment]
SAME HERE I'VE DEBUGGED IT
file:///root/Peek%202020-06-27%2013-08.gif
