### ISSUE TITLE
user-agent from requirements installed in wrong directory and not being located with run command 

### ISSUE THREAD

**Issue by dallasmaverick** [OWASP/QRLJacking#103]
Hello,

I installed QRLJacker as a normal user but noticed that the requirements.txt file installed everything in correct location except user-agent. See the image below.

![useragent](https://user-images.githubusercontent.com/66530056/83951346-d8db3d80-a7fe-11ea-91a0-f1e22d9ccf53.JPG)
Now, when i run the tool as non root user, I get an error as shown below.

![nonroot](https://user-images.githubusercontent.com/66530056/83951459-9e25d500-a7ff-11ea-8f69-c83f349d7253.JPG)
If I try to run it as a root user, I get the user-agent not found error. Not sure what is going on. Any help is appreciated.

![useragent1](https://user-images.githubusercontent.com/66530056/83951538-12607880-a800-11ea-821f-c5b996831d85.JPG)

Thank you

**Comment by melbadry9** [comment]
The following command should fix the problem. 

• sudo pip3 install -r requirements.txt
• sudo python3 QRLJacker.py
