### ISSUE TITLE
File "QRLJacker.py", line 19     print "[*] Error Importing Exterinal Libraries"

### ISSUE THREAD

**Issue by Evink-rook** [OWASP/QRLJacking#104]
I cloned qrljacking from https://github.com/d00b11/QRLJacking-1.git
Every thing happened fine until installing requirement.txt
         
  #    pip install -r requirements.txt 
Requirement already satisfied: requests>=2.11.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.23.0)
Requirement already satisfied: Pillow>=3.3.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (6.2.1)
Requirement already satisfied: selenium==2.53.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (2.53.1)
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (5.0.0)

 Then I change QRLJacker.py to executive mod 

          #chmod +x QRLJacker.py

All seems fine until this .

Then the error accrued  at the last step on execution as 
      #python  QRLJacker.py
         File "QRLJacker.py", line 19
    print "[*] Error Importing Exterinal Libraries"
                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[*] Error Importing Exterinal Libraries")?

#######
Anybody can help me to solve this error .
I tried some of similar issues solutions to solve but nothing caught exact to solve it

**Comment by host2india** [comment]
Please do  python3  QRLJacker.py

**Comment by host2india** [comment]
oot@kali:/home/kali# cd Desktop/
root@kali:/home/kali/Desktop# cd QRLJacking/QRLJacker
root@kali:/home/kali/Desktop/QRLJacking/QRLJacker# pip install -r requirements.txt
Requirement already satisfied: terminaltables>=3.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: selenium>=3.141.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (4.0.0a1)
Requirement already satisfied: Pillow>=5.4.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (6.2.1)
Requirement already satisfied: Jinja2>=2.10 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (2.11.2)
Collecting user-agent>=0.1.9
  Using cached user_agent-0.1.9.tar.gz (20 kB)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from user-agent>=0.1.9->-r requirements.txt (line 5)) (1.15.0)
Building wheels for collected packages: user-agent
  Building wheel for user-agent (setup.py) ... done
  Created wheel for user-agent: filename=user_agent-0.1.9-py3-none-any.whl size=18806 sha256=be309f4eade2633ae35a48ac385ef20ba1d6a4a617e4d06b30175357c9718dda
  Stored in directory: /root/.cache/pip/wheels/12/0f/dc/cae279f7cd787a637a9fe083ce976d9dfefc034637b92e3f6c
Successfully built user-agent
Installing collected packages: user-agent
Successfully installed user-agent-0.1.9
>>>>>Check user agent installed<<<<<<<<<<<<<<<

**Comment by Evink-rook** [comment]
> oot@kali:/home/kali# cd Desktop/
> root@kali:/home/kali/Desktop# cd QRLJacking/QRLJacker
> root@kali:/home/kali/Desktop/QRLJacking/QRLJacker# pip install -r requirements.txt
> Requirement already satisfied: terminaltables>=3.1.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (3.1.0)
> Requirement already satisfied: selenium>=3.141.0 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (4.0.0a1)
> Requirement already satisfied: Pillow>=5.4.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (6.2.1)
> Requirement already satisfied: Jinja2>=2.10 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 4)) (2.11.2)
> Collecting user-agent>=0.1.9
> Using cached user_agent-0.1.9.tar.gz (20 kB)
> Requirement already satisfied: six in /usr/lib/python3/dist-packages (from user-agent>=0.1.9->-r requirements.txt (line 5)) (1.15.0)
> Building wheels for collected packages: user-agent
> Building wheel for user-agent (setup.py) ... done
> Created wheel for user-agent: filename=user_agent-0.1.9-py3-none-any.whl size=18806 sha256=be309f4eade2633ae35a48ac385ef20ba1d6a4a617e4d06b30175357c9718dda
> Stored in directory: /root/.cache/pip/wheels/12/0f/dc/cae279f7cd787a637a9fe083ce976d9dfefc034637b92e3f6c
> Successfully built user-agent
> Installing collected packages: user-agent
> Successfully installed user-agent-0.1.9

> 
> > > > > > Check user agent installed<<<<<<<<<<<<<<<

I installed requirement.txt using both pip and python3.7 -m pip command

BUT There is no such thing installed as USER-AGENT

The result I got for the command is just

┌─[root@Evink]─[/tools/QRLJacking-1/QrlJacking-Framework]
└──╼ #pip install -r requirements.txt
Requirement already satisfied: requests>=2.11.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.23.0)
Requirement already satisfied: Pillow>=3.3.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (6.2.1)
Requirement already satisfied: selenium==2.53.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (2.53.1)
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (5.0.0)
┌─[root@Evink]─[/tools/QRLJacking-1/QrlJacking-Framework]
└──╼ #python3.7 -m pip  install -r requirements.txt
Requirement already satisfied: requests>=2.11.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.23.0)
Requirement already satisfied: Pillow>=3.3.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (6.2.1)
Requirement already satisfied: selenium==2.53.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (2.53.1)
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (5.0.0)

**Comment by Evink-rook** [comment]
> Please do python3 QRLJacker.py
 Thanks for your response!!!

As you said I tried to run it using pytthon3 and python3.7
But still I got the same error!

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

┌─[root@Evink]─[/tools/QRLJacking-1/QrlJacking-Framework]
└──╼ #pip3.7 install -r requirements.txt 
Requirement already satisfied: requests>=2.11.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2.23.0)
Requirement already satisfied: Pillow>=3.3.1 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (6.2.1)
Requirement already satisfied: selenium==2.53.1 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 3)) (2.53.1)
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 4)) (5.0.0)
┌─[root@Evink]─[/tools/QRLJacking-1/QrlJacking-Framework]
└──╼ #chmod +x QRLJacker.py
┌─[root@Evink]─[/tools/QRLJacking-1/QrlJacking-Framework]
└──╼ #python3 QRLJacker.py
  File "QRLJacker.py", line 19
    print "[*] Error Importing Exterinal Libraries"
                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[*] Error Importing Exterinal Libraries")?
┌─[✗]─[root@Evink]─[/tools/QRLJacking-1/QrlJacking-Framework]
└──╼ #python3.7 QRLJacker.py
  File "QRLJacker.py", line 19                                                      
    print "[*] Error Importing Exterinal Libraries"
                                                  ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[*] Error Importing Exterinal Libraries")?

**Comment by melbadry9** [comment]
The following commands should fix the problem.

• sudo apt-get install python3-pip
• pip3 install -r requirements.txt
• python3 QRLJacker.py
