### ISSUE TITLE
Exception in thread Webserver manager thread: Traceback (most recent call last):

### ISSUE THREAD

**Issue by malitongtong** [OWASP/QRLJacking#105]
![er](https://user-images.githubusercontent.com/66511547/84942982-4e6dc600-b0a9-11ea-965d-da317cff1290.png)

what should i do to fix this? thank you.. i stucked here

**Comment by Raj-esh-cell** [comment]
How to solve this

**Comment by hari2229** [comment]
same problem here... what is the solution..pls

**Comment by melbadry9** [comment]
Make sure to run with root privileges.
