### ISSUE TITLE
Unable to launch QRLJacking.py on Mac

### ISSUE THREAD

**Issue by miluve** [OWASP/QRLJacking#111]
Hello guys,

I am getting the below error trying to launch python on my Mac OS Catalina. Can you please help

<img width="1129" alt="Screenshot 2020-08-25 at 14 09 01" src="https://user-images.githubusercontent.com/70210604/91178693-6aab6600-e6dd-11ea-8ddf-b6edee6d4fcf.png">

**Comment by melbadry9** [comment]
Python 2 is not supported.
