### ISSUE TITLE
Gowtham

### ISSUE THREAD

**Issue by gowthamviswas** [OWASP/QRLJacking#117]
I'm unable run QrlJacker.py. please help me..
All the requirements in requirements.txt are installed, but im unable to run the script.

root@kali:~/opt/QRLJacking/QRLJacker# python3.7 -m pip install -r requirements.txt
Requirement already satisfied: terminaltables>=3.1.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: selenium>=3.141.0 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (3.141.0)
Requirement already satisfied: Pillow>=5.4.1 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (7.2.0)
Requirement already satisfied: Jinja2>=2.10 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 4)) (2.11.2)
Requirement already satisfied: user-agent>=0.1.9 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 5)) (0.1.9)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/site-packages (from selenium>=3.141.0->-r requirements.txt (line 2)) (1.25.10)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/site-packages (from Jinja2>=2.10->-r requirements.txt (line 4)) (1.1.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from user-agent>=0.1.9->-r requirements.txt (line 5)) (1.15.0)
 

root@kali:~/opt/QRLJacking/QRLJacker# python3.7 QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/opt/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'

**Comment by melbadry9** [comment]
- Run the following command, and this should fix missing module error.

```bash
pip3 install readline
```
