### ISSUE TITLE
Cannot recognize chrome or chromium  browser

### ISSUE THREAD

**Issue by xrami** [OWASP/QRLJacking#12]
![147526457663504](https://cloud.githubusercontent.com/assets/15074563/18990713/711a3770-871c-11e6-964d-dcf6fdeaf523.png)

**Comment by D4Vinci** [comment]
What is the os you are using ?

**Comment by xrami** [comment]
I use Linux Deepin Os

**Comment by D4Vinci** [comment]
Okay,it's a bug in the chromedriver.
Seems like if the chrome driver is not in your path you have to pass it in as an argument to the constructor.
# Try:
 `pip install chromedriver`

**if the framework didn't work do the following..**

## For Windows
- You should specify the executable file path, not the directory path that contains the executable.

 `driver = webdriver.Chrome(executable_path=r"C:\Chrome\chromedriver.exe")`

## For Linux
- Check you have installed latest version of chrome brwoser-> "chromium-browser -version" 
- If not, install latest version of chrome "sudo apt-get install chromium-browser"

## For Mac
 `brew install chromedriver`
That should put the chromedriver in your path and you should be all set.

**Comment by xrami** [comment]
Chromium version 
Version 51.0.2704.79 built on Debian stretch/sid, running on Debian 8.0 (64-bit)
Chrome version
Version 52.0.2743.116 (64-bit)

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!
