### ISSUE TITLE
QRLJacker - Run is not recognized as an internal command!

### ISSUE THREAD

**Issue by ashu223** [OWASP/QRLJacking#127]
When i run grabber/whatsapp, im getting this error
"Run is not recognized as an internal command!"

In the final step im getting this error.. all other things are working fine
![QRL error 2](https://user-images.githubusercontent.com/55798020/99838289-e5760700-2b8e-11eb-9332-e2b9773e716a.png)

**Comment by melbadry9** [comment]
Can you please provide the version of python which you're using?

**Comment by ashu223** [comment]
> 
> 
> Can you please provide the version of python which you're using?

Python 3.8.6

Before run command was working fine but localhost server not working.
Now i have updated my Firefox to latest version, getting error in Final "run" command.

**Comment by melbadry9** [comment]
This is a known issue with python 3.8, We currently working on fixing this. 

You can use python 3.7 to avoid this problem.
