### ISSUE TITLE
Session loop and not able to interact with session because of redirected to whatsapp web website

### ISSUE THREAD

**Issue by v3nki1234** [OWASP/QRLJacking#129]
i am using kali linux 2020.3 and mozilla firefox 68.10.0esr

i installed all requirements and 64 bit geckodriver  hence i scanned that QR code with my own whatapp account  then i got continues session loop 

![loop](https://user-images.githubusercontent.com/73926104/99979535-3410e480-2dcd-11eb-9021-5dfde84d04c5.PNG)

and while interacting with any sessioin using session number

sessions -i 1

then victim session is not open . always opens only real whatsapp web 
![lat](https://user-images.githubusercontent.com/73926104/99979900-a41f6a80-2dcd-11eb-8ecd-bfa71d0c9695.PNG)

**Comment by melbadry9** [comment]
This is a known issue.

**Comment by v3nki1234** [comment]
how to get rid of that issue session loop and redirected to  WhatsApp web 

and please make docker image for Qrljacking

**Comment by melbadry9** [comment]
Thanks for your suggestion. We currently working on fixing this issue.

**Comment by never-sur** [comment]
The same problem. How long we should you wait until you fix it? Sorry if I say something no correct, my Eng is not good. Hope you understand correctly
