### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by SYCAREX** [OWASP/QRLJacking#136]
Traceback (most recent call last):
  File "QrlJacker.py", line 16, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax
![Ekran Alıntısı](https://user-images.githubusercontent.com/65655830/107627972-0d967300-6c71-11eb-805c-f7cfcddf6271.PNG)

**Comment by melbadry9** [comment]
As mentioned in install instruction only 'python3` is supported.
