### ISSUE TITLE
run is not recognized as an internal command

### ISSUE THREAD

**Issue by rxu293** [OWASP/QRLJacking#137]
Python version: 3.7.7
OS:  MacOS Big Sur, version: 11.1

I am pretty sure that I strictly followed every detail in the instruction.
However, bugs still come out, please help.

This is what I got when trying to run it.
QrlJacker Module(grabber/whatsapp) > run
[!] run is not recognized as an internal command !
[+] Maybe you meant : , runreload, refresh, resource
[+] Type help or ? to learn more..

Under debug mode:
QrlJacker Module(grabber/whatsapp) > debug
[+] Debug mode enabled!

QrlJacker Module(grabber/whatsapp) > run
Exception -> module 'core.Cli' has no attribute 'command_run'
    Input -> run
Trackback -> 
Traceback (most recent call last):
  File "/Users/ricky/Desktop/QRLJacking/QRLJacker/core/module.py", line 51, in handle
    exec("Cli.command_{}(args)".format(head))
  File "<string>", line 1, in <module>
AttributeError: module 'core.Cli' has no attribute 'command_run'

Under verbose mode:
QrlJacker Module(grabber/whatsapp) > run
Exception -> module 'core.Cli' has no attribute 'command_run'
    Input -> run
Trackback -> 
Traceback (most recent call last):
  File "/Users/ricky/Desktop/QRLJacking/QRLJacker/core/module.py", line 51, in handle
    exec("Cli.command_{}(args)".format(head))
  File "<string>", line 1, in <module>
AttributeError: module 'core.Cli' has no attribute 'command_run'
[!] run is not recognized as an internal command !
[+] Maybe you meant : , runreload, refresh, resource
[+] Type help or ? to learn more..

**Comment by NamanPrakash** [comment]
You should try it in Kali Linux then it will work

**Comment by NamanPrakash** [comment]
Ok before it was working on me but now it also shows the same error

**Comment by melbadry9** [comment]
Can't reproduce this issue, try clone fresh copy of QRLJacking.

**Comment by cristbaby** [comment]
TEngo el mismo problema, sospecho que es la version de firefox

**Comment by Desartstudio** [comment]
Same error, is firefox ..in my case, upgrade it

**Comment by z41b1337** [comment]
I'm using Kali Linux with the latest version of firefox but still facing the same error. any idea what to do?
