### ISSUE TITLE
free(): invalid pointer Aborted

### ISSUE THREAD

**Issue by Spider8511** [OWASP/QRLJacking#140]
after start application this message found

**Comment by melbadry9** [comment]
Can you please provide more info about this issue and how to reproduce it?

**Comment by Spider8511** [comment]
QrlJacker > help/?
free(): invalid pointer
Aborted

**Comment by melbadry9** [comment]
You can use either `help` or `?` not both.

**Comment by Spider8511** [comment]
QrlJacker > list
free(): invalid pointer
Aborted

**Comment by code-with-santanu** [comment]
I am facing same problem
QrlJacker > list
free(): invalid pointer
Aborted

**Comment by john-whick-13** [comment]
any solution for this error
