### ISSUE TITLE
session interaction started but couldn't open browser

### ISSUE THREAD

**Issue by naveenkumar6284** [OWASP/QRLJacking#142]
I was able to get session successfully but when i tried to interact with the session it says as 
[+] Starting interaction with (0)...
[!] Couldn't open browser to view session!

if anyone encountered this issue and was able to resolve it please help me to resolve it.
Also can anyone tell me why this issue is encountered.

![issue](https://user-images.githubusercontent.com/73075519/115376375-45c7ae00-a1ec-11eb-84d6-cebeb485023f.jpg)

**Comment by cristbaby** [comment]
a mi me pasa lo mismo, ¿encontraste la respuesta?
