### ISSUE TITLE
QRL Code is being replacing

### ISSUE THREAD

**Issue by karthik07m** [OWASP/QRLJacking#143]
After some QRL code image is being replaced by "CLICK TO RELOAD  QR CODE". Please find the image below
![Capture](https://user-images.githubusercontent.com/10569445/115395368-6bab7d80-a201-11eb-916c-038f7210e010.PNG)

**Comment by demurk** [comment]
Had same problem. You need to change this file QRLJacking/QRLJacker/core/modules/grabber/whatsapp.py
Replace `img_reload_button = '/html/body/div[1]/div/div/div[2]/div[1]/div/div[2]/div/span/div'` string with
`img_reload_button = '/html/body/div/div[1]/div/div[2]/div[1]/div/div[2]/div/span/button'`

This worked for me

**Comment by cristbaby** [comment]
Me funcionó a la perfección
