### ISSUE TITLE
Session storage issue

### ISSUE THREAD

**Issue by GhaziJi** [OWASP/QRLJacking#144]
QR Jacker is not storing session properly. 

Description:
If you scan multiple devices with same server link, it will store the last scanned device in the same session. For example, if I scan device A, B, and C then ideally it shall store it in session 1, 2, and 3 respectively. However, what is happening here is that it stores session of device A as session 1, then stores device B's session as session 1 and removes device A's session and so on.

**Comment by melbadry9** [comment]
This is known issue #128
