### ISSUE TITLE
error in command line sessions

### ISSUE THREAD

**Issue by fazilbaig1** [OWASP/QRLJacking#145]
after getting session when i restart pc then this type of error is occured  please help me #developer

**Comment by melbadry9** [comment]
Can you provide more details about this issue?

**Comment by melbadry9** [comment]
This is a known issue #128

**Comment by fazilbaig1** [comment]
how to solve this issue

**Comment by melbadry9** [comment]
@fazilbaig1, We are working on fixing this issue. This Issue is been tracked in #128

**Comment by fazilbaig1** [comment]
i said u how i solved this issue  brother now u can fix only temp files
removed from temp folder
