### ISSUE TITLE
double free or corruption (out) 

### ISSUE THREAD

**Issue by atvicente** [OWASP/QRLJacking#146]
Hi guys, I have a problem.  After putting the command to start QrlJaking and after typing any command in the panel, I get this "double free or corruption (out)" error.  I don't know if it has something to do with the fact that when installing requirements.txt I used pip and then pip3
![C0B26FFC-D3C6-4092-AC48-8CA9ED3F89F2](https://user-images.githubusercontent.com/83570487/117764104-903bb980-b1f1-11eb-9c4c-4e063e56298f.jpeg)

@melbadry9
@samm0uda
@Lekssays
@0xGuindi
@Kiro24
@MohamedAbdultawab
@mohmyo
@OmarMerghany
@TheRubick
@mikeashi
@mxfoxawy

**Comment by melbadry9** [comment]
I can't reproduce this issue, Can you provide more details?

**Comment by atvicente** [comment]
I had to create a virtual environment and it worked for me
