### ISSUE TITLE
I'm getting this exception 🙂

### ISSUE THREAD

**Issue by shuence** [OWASP/QRLJacking#154]
I'm using 
Os :- Parrot Os
Python 3.9.2
Letest geckodriver for linux 

![SAVE_20210717_094821.jpg](https://user-images.githubusercontent.com/65482186/126025253-3a6a2db0-eacf-4ad1-8e14-8c675a9794ad.jpg)

**Comment by melbadry9** [comment]
Please make sure to check closed/pinned issues.
