### ISSUE TITLE
Can not call any WebBrowsers   

### ISSUE THREAD

**Issue by kalaireas** [OWASP/QRLJacking#16]
Dear contributors, 

Found that the latest build throwing the follow error, tested on Kali Linux 2016.2  & Ubuntu 16.04

 [*] Starting victim session on http://localhost:1337
 Error: 
 Can not call any WebBrowsers
  Check your Installed Browsers!

**Comment by D4Vinci** [comment]
It's a bug in the selenium webdriver not us
See #12

**Comment by rasimakgun** [comment]
How to solve?
Can you help me please .

**Comment by rasimakgun** [comment]
Linux 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2
Web browser: Firefox Version 60.2.0esr (64-bit)

**Comment by bharathwajan** [comment]
i am also getting the same error , i had many methods but its not working

**Comment by ksonone** [comment]
have you tried this?

1. Download geckodriver (for Mozilla Firefox Browser) 
   To download type in terminal :- 
   - git clone https://github.com/mozilla/geckodriver
2. then
  - chmod +x geckodriver
3. Do following steps 
   - sudo mv -f geckodriver /usr/local/share/geckodriver
   - sudo ln -s /usr/local/share/geckodriver /usr/local/bin/geckodriver
   - sudo ln -s /usr/local/share/geckodriver /usr/bin/geckodriver
4. That's all.

**Comment by prashhh0231** [comment]
[*] Starting victim session on http://localhost:1337
Error:
Can not call any WebBrowsers
Check your Installed Browsers!
this error found.
what can i do?

**Comment by bharathwajan** [comment]
Thank you for your kind reply

**Comment by mylinux2000** [comment]
*] Starting victim session on http://localhost:1337
Error:
Can not call any WebBrowsers
Check your Installed Browsers!
how to fix this error ....

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!

**Comment by historyhacking** [comment]
### **help me..!!!**
*] Starting victim session on http://localhost:1337
Error:
Can not call any WebBrowsers
Check your Installed Browsers!

how can the qrl run properly

**Comment by alinahid** [comment]
Still showing cannot open any browser..can anyone help

**Comment by olimpo88** [comment]
In the following comment I explained how to solve it **in linux**. I've tried it on ubuntu 18 and kali.

https://github.com/OWASP/QRLJacking/issues/29#issuecomment-473978257
