### ISSUE TITLE
Command injection

### ISSUE THREAD

**Issue by lnxg33k** [OWASP/QRLJacking#2]
`os.system()` has been deprecated since Python 2.6 in favor of the subprocess module.

Use subprocess with shell=False. It will protect you against most of the risk associated with piping commands.

<img width="1440" alt="screen shot 2016-09-03 at 6 52 04 am" src="https://cloud.githubusercontent.com/assets/1170490/18222542/2cec7cae-71a3-11e6-8824-210459b687f7.png">

**Comment by SymbianSyMoh** [comment]
Thanks a lot @lnxg33k, We (you) will look into this 👍

**Comment by D4Vinci** [comment]
It's now solved I think :smile:
