### ISSUE TITLE
hijacking doesn't work on a remote server 

### ISSUE THREAD

**Issue by Virgula0** [OWASP/QRLJacking#20]
I tried to use a remote server (altervista) uploading qrhandler.php and phishing.html and setting Greasemonkey but it doesn't work for me.... 
Below pictures... Can you help me? 
p.s server doesn't have SSL is maybe due to this?
Thank You

Video demonstration:
[![Watch the video](https://user-images.githubusercontent.com/16546435/30524835-539c7dda-9bfb-11e7-8ac9-adf332848c63.png)](https://youtu.be/N6cxx46k_s8)

Pictures:

<img width="1137" alt="schermata 2017-09-17 alle 22 53 39" src="https://user-images.githubusercontent.com/16546435/30524832-4e95b608-9bfb-11e7-887f-20e6709971c0.png">

<img width="1137" alt="schermata 2017-09-17 alle 22 53 24" src="https://user-images.githubusercontent.com/16546435/30524833-506b299a-9bfb-11e7-8feb-53650149b535.png">

<img width="1136" alt="schermata 2017-09-17 alle 22 53 56" src="https://user-images.githubusercontent.com/16546435/30524829-4558c97c-9bfb-11e7-8e48-d9c1d9f389bf.png">

<img width="1138" alt="schermata 2017-09-17 alle 22 54 25" src="https://user-images.githubusercontent.com/16546435/30524835-539c7dda-9bfb-11e7-8ac9-adf332848c63.png">

**Comment by Swetabhsuman8** [comment]
**No, its not about SSL**. you need to bypass firewall and you need to open port then it will work on remote server.

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!
