### ISSUE TITLE
invalid pointer

### ISSUE THREAD

**Issue by john-whick-13** [OWASP/QRLJacking#205]
after running the tool i got this error 

QrlJacker > use grabber/whatsapp

free(): invalid pointer

Aborted

root@kali:~/tools/QRLJacking/QRLJacker#

**Comment by LucaReggiannini** [comment]
Please launch Qrljacker and use "verbose" and "debug" commands to increment the verbosity of the output. Write here the full output (from the program start to the error). 

  
Please post the output of `uname -a && python3 --version` too. If you are using another version of python (for example 3.8) please use `uname -a && python3.8 --version`.

Consider that Qrljacker was updated just today so maybe is worth for you to download again this project and retry.

**Comment by john-whick-13** [comment]
thanks for your kindly response itinstalled now
