### ISSUE TITLE
QR-code won't load

### ISSUE THREAD

**Issue by Bunder99** [OWASP/QRLJacking#21]
Hi! I use QRL-jacking framework and get the error: when the script opens a new window of Firefox and follows to https://web.whatsapp.com/, the QR-code can't download. The browser says: you use an incompatible Web driver. But when I open the same page on my main window of Firefox, the QR-code is presented.
I use Firefox 52.3.0 (64 bit) and selenium==2.53.1. I tried to use other selenium versions, but I did't get the profit. What should I do?

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!
