### ISSUE TITLE
Kali Linux Arm64/Aarch64 Support???

### ISSUE THREAD

**Issue by Gary-Cod** [OWASP/QRLJacking#213]
Just wondering if this project will get support to work on Linux Aarch/Arm64 ??
- Tried few times before but never worked because it kept complaining about geckodriver. I tried to search any possible solution online but i couldn't get it to work for Arm64 (On Kali Linux & Ubuntu Arm64 distrors). Than gave up because couldn't find any help or updates. Just checked today and saw some updates ???

**Comment by LucaReggiannini** [comment]
Never tried on this architecture but there is a Geckodriver release for Aarch64 https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux-aarch64.tar.gz

Is that what you are looking for?

**Comment by Gary-Cod** [comment]
OS: Parrot OS 5.3 (Electro Ara) aarch64
- Linux parrot 6.1.0-1parrot1-arm64 #1 SMP Parrot 6.1.15-1parrot1 (2023-04-25) aarch64 GNU/Linux

Python 3.9 --version
- Python 3.9.2

Geckodriver --version ("geckodriver-v0.33.0-linux-aarch64")
- geckodriver 0.33.0


------------------------------------------


python3.9 QrlJacker.py --debug --verbose
QrlJacker > use grabber/whatsapp

QrlJacker Module(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

QrlJacker Module(grabber/whatsapp) > Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/parrot/Downloads/QRLJacking/QRLJacker/core/browser.py", line 198, in serve_module
    webserver.start_serving(host)
  File "/home/parrot/Downloads/QRLJacking/QRLJacker/core/module_utils.py", line 33, in start_serving
    self.httpd = ReusableTCPServer( (host, self.port), MyHandler)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied

[!] KeyboardInterrupt use exit command!


Can you please help !!!

**Comment by LucaReggiannini** [comment]
I see a `PermissionError: [Errno 13] Permission denied`: did you try to set a port **higher than 1024**? You can do it with:
`set port 1234`
before using the `run` command.
As an alternative you can try to run the program as root with `sudo python3.9 QrlJacker.py`

**Comment by Gary-Cod** [comment]
Yes 
On Parrot OS 5.3 (Electro Ara) aarch64 ----> its working perfectly
Thanks for your amazing work & help !!!
