### ISSUE TITLE
How to get connection persist ?

### ISSUE THREAD

**Issue by ARiITRrIX** [OWASP/QRLJacking#22]
Hello friends

so first of all i would like to tell my thx to the developer. GREAT JOB ;) 

But i have question when I got the connection how can I got it permanently. In another video the Youtuber show copy an code in secrets.txt file and after that if i would like to connect i copy this code and paste it to the https://www.web.whatsapp.com/ in inspect elements console. How can I make this with QRLJacking.

thx for all answers ;)

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!
