### ISSUE TITLE
Error:   Can not call any WebBrowsers   Check your Installed Browsers!

### ISSUE THREAD

**Issue by th3j0ker** [OWASP/QRLJacking#23]
I've installed all requirements, it seems like some sort of version conflict between various python versions but i am not able to understand the exact cause, I even tried installing chromium web driver instead of selenium but neither of them would work. any solutions? 

I could not find any logs in this script which I could refer.
---------------------error---------------------
[*] Starting victim session on http://localhost:1337
 Error: 
 Can not call any WebBrowsers
  Check your Installed Browsers!
-------------------------------------------------

--------------things tried----------------
python -m pip install selenium (firefox)
pip install chromedriver
------------------------------

--------------system_details---------
OS: kali linux
Kernel: x86_64 Linux 4.14.0-kali3-amd64
-------------------------------------------

**Comment by th3j0ker** [comment]
some progress,
i installed the geckodrivers that were missing, i think selenium drivers were dependent on it. now the firefox window pops up but no response on terminal, it just reads "[*] Starting victim session on http://localhost:1337"

when i open my localhost, it doesnot show my any QR code, just that dummy html file..

**Comment by th3j0ker** [comment]
fixed!
as I stated before, it was missing some python libraries
anyone facing issues same as me should type the following.
---------------------------
python -m pip install -r requirements.txt

**Comment by th3j0ker** [comment]
**fixed!**
as I stated before, it was missing some python libraries
anyone facing issues same as me should type the following.

python -m pip install -r requirements.txt

**Comment by th3j0ker** [comment]
`fixed!`

**Comment by hanuga** [comment]
not working out still, unable to fix the error. any lead?

**Comment by prashhh0231** [comment]
All above given tricks does not working please help me

**Comment by MedyThawedy81** [comment]
What is the solution please?

**Comment by deepdarksa** [comment]
guys pls all of you java scripters and qrl owners dont know how to fix this problem

**Comment by deepdarksa** [comment]
will sometimes in life its up to you as soon as you get into this door 
i fixd this issue try this installing CHROMIUM and thats it https://www.youtube.com/watch?v=GdUaG_mYMi0

**Comment by olimpo88** [comment]
In the following comment I explained how to solve it **in linux**. I've tried it on ubuntu 18 and kali

https://github.com/OWASP/QRLJacking/issues/29#issuecomment-473978257

**Comment by itsrohit486** [comment]
Stiil getting Error plzz help me

**Comment by D4Vinci** [comment]
Checkout the new version
