### ISSUE TITLE
QRl Jacking on termuda 

### ISSUE THREAD

**Issue by oneisme** [OWASP/QRLJacking#24]
If QRL Jacking can be install in termux android. Wow amazing.
Cantik you help

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!

**Comment by 8590106078** [comment]
I dont know how to do qrl jacking 
Could you study me .....
