### ISSUE TITLE
OSX install : need some  

### ISSUE THREAD

**Issue by olygoelements** [OWASP/QRLJacking#27]
when I put this commande sudo pip install -r requirements.txt

the installation will stop with this information…
matplotlib 1.3.1 requires nose, which is not installed.
matplotlib 1.3.1 requires tornado, which is not installed.

can you help me?
thanks

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!
