### ISSUE TITLE
Python Error 

### ISSUE THREAD

**Issue by hanuga** [OWASP/QRLJacking#28]
[*] Starting victim session on http://localhost:1337
 Error:
 Can not call any WebBrowsers
  Check your Installed Browsers!

Using Windows 10, went through the link https://github.com/OWASP/QRLJacking/issues/12 but still face the error.

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!
