### ISSUE TITLE
Error: Can not call any WebBrowsers in Ubuntu 18.04

### ISSUE THREAD

**Issue by reaganscofield** [OWASP/QRLJacking#29]

**Comment by coolpixgnu** [comment]
Hi @reaganscofield for me worked in OSX:
check this: chromedriver: migrate to cask (https://github.com/Homebrew/homebrew-core/pull/25566)
Process:

$ brew cask install chromedriver
==> Satisfying dependencies
==> Downloading https://chromedriver.storage.googleapis.com/2.45/chromedriver_mac64.zip
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'chromedriver'.
==> Installing Cask chromedriver
==> Linking Binary 'chromedriver' to '/usr/local/bin/chromedriver'.
🍺  chromedriver was successfully installed!

Kind regards

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!

**Comment by olimpo88** [comment]
**For Linux**

First install the dependencies of the project with pip `pip install -r requirements.txt`

Download or copy the following script
https://github.com/olimpo88/Drivers-for-browsers/tree/master

Make the file executable `chmod +x SCRIPTNAME.sh`

Run './SCRIPTNAME.sh'

Finally, you can now run QrlJacking-Framework  :blush:
