### ISSUE TITLE
Suggestion of a massive random implementation

### ISSUE THREAD

**Issue by SaeedHashem** [OWASP/QRLJacking#3]
The current version of [QRLJacker.py](https://github.com/OWASP/QRLJacking/blob/master/QrlJacking-Framework/QRLJacker.py) basically performs a single targeted attack , which cause some limitations to be present on the Social Engineering phishing attack vector .

``` python
try:
            img = driver.find_elements_by_tag_name('img')[0]
            src = img.get_attribute('src').replace("data:image/png;base64,","")
            print " [*] QR code image detected !"
            print " [*] Downloading the image..."
            binary_data = a2b_base64(src)
            qr = open("tmp.png","wb")
            qr.write(binary_data)
            print " [*] Saved To tmp.png"
            qr.close()
            time.sleep(5)
            continue
        except:
            break
```

It breaks after the QR code has been scanned by the victim as there's no `img` on the current session anymore .

Would be more reliable if , instead of breaking , the code returns to a specific function that starts a new session with a new QR code and continues updating the `tmp.png` with the new QR code to re-setup the trap for more potential victims . That's more reliable for a massive phishing attack vector .

Starting different newer sessions on the same browser could be a tough job though , I think you'll need to code some of the techniques used in [MultiFox](https://addons.mozilla.org/en-US/firefox/addon/multifox/) and [Session Buddy](https://chrome.google.com/webstore/detail/session-buddy/edacconmaakjimmfgnblocblbcdcpbko) inside the framework ,  maybe you'll ask the user to install those on his browser if he wants to use this attack vector , and then try to access their features using your python code .

Anyways , the massive random attack vector shouldn't be the default attack vector though , it would be more convenient if you prompt the user to choose between the `Single targeted attack` and the `Massive random attack` .

**Comment by D4Vinci** [comment]
Good idea saed,I will keep that in my mind :+1:
Thanks. :smile:

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!
