### ISSUE TITLE
[*] Error Importing Exterinal Libraries [*] Trying install it using the requirements.txt file..

### ISSUE THREAD

**Issue by midoubaghdad** [OWASP/QRLJacking#30]
oot@kali:~/QRLJacking/QrlJacking-Framework# python QRLJacker.py
[*] Error Importing Exterinal Libraries
[*] Trying install it using the requirements.txt file..

Requirement already satisfied: requests>=2.11.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (2.18.4)
Requirement already satisfied: Pillow>=3.3.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (5.2.0)
Requirement already satisfied: selenium==3.14.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (3.14.1)
Requirement already satisfied: configparser>=3.5.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (3.5.1)
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages (from selenium==3.14.1->-r requirements.txt (line 3)) (1.22)
Traceback (most recent call last):
  File "QRLJacker.py", line 36, in <module>
    settings = configparser.ConfigParser()
NameError: name 'configparser' is not defined

**Comment by 0xInfection** [comment]
Try `pip install configparser==3.3.0.post2`.

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!
