### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by MahmoudJad** [OWASP/QRLJacking#34]
i can't install the QRLJacking, every time i tried to install it i get requeriments.txt erro

**Comment by D4Vinci** [comment]
Wait for the new version we are working on

**Comment by manan2501** [comment]
> Wait for the new version we are working on

How much time would it take? approx?
And are there in new features, or you are trying to solve errors.

**Comment by D4Vinci** [comment]
Lol! we just pushed the new version yesterday :smile:
