### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by elieelias** [OWASP/QRLJacking#35]
root@kali:~/Desktop/QRLJacking-master/QRLJacker# python QrlJacker.py
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Desktop/QRLJacking-master/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax

**Comment by manan2501** [comment]
Traceback (most recent call last):
  File "./QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Desktop/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/root/Desktop/QRLJacking/QRLJacker/core/utils.py", line 5, in <module>
    from terminaltables import AsciiTable as table
ModuleNotFoundError: No module named 'terminaltables'

**Comment by SymbianSyMoh** [comment]
Follow the installation guidelines and use Python3 instead of 2.

**Comment by nlona** [comment]
Got same problem
 ``root@kali:~/QRLJacking/QRLJacker# pip install -r requirements.txt 
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: terminaltables>=3.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: selenium>=3.141.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (3.141.0)
Requirement already satisfied: Pillow>=5.4.1 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (5.4.1)
Requirement already satisfied: Jinja2>=2.10 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (2.10)
Requirement already satisfied: user-agent>=0.1.9 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (0.1.9)
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages (from selenium>=3.141.0->-r requirements.txt (line 2)) (1.24.1)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from user-agent>=0.1.9->-r requirements.txt (line 5)) (1.12.0)
root@kali:~/QRLJacking/QRLJacker# python QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax
``

**Comment by YoAkky** [comment]
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax

**Comment by D4Vinci** [comment]
For SyntaxError, see this pinned issue #47
