### ISSUE TITLE
problem when i try to lunch QrlJacker.py 

### ISSUE THREAD

**Issue by BlackScorpion10** [OWASP/QRLJacking#38]
this is the problem 
$python QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^

**Comment by D4Vinci** [comment]
Read the fuckin instructions!
The framework isn't working on python 2 as I said in it!!

**Comment by BlackScorpion10** [comment]
:~/QRLJacking/QRLJacker# python3 QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/root/QRLJacking/QRLJacker/core/utils.py", line 5, in <module>
    from terminaltables import AsciiTable as table
ModuleNotFoundError: No module named 'terminaltables'

**Comment by D4Vinci** [comment]
WTF!
If you installed the requirements as I said in the instructions you won't see that error!!!!

**Comment by BlackScorpion10** [comment]
root@kali:~/QRLJacking/QRLJacker# ls
browser.py  core  docs  QrlJacker.py  README.md  requirements.txt  Screenshots  sessions
root@kali:~/QRLJacking/QRLJacker# pip install -r requirements.txt
Requirement already satisfied: terminaltables>=3.1.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (3.1.0)
Requirement already satisfied: selenium>=3.141.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (3.141.0)
Requirement already satisfied: Pillow>=5.4.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (6.0.0)
Requirement already satisfied: Jinja2>=2.10 in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (2.10)
Requirement already satisfied: user-agent>=0.1.9 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (0.1.9)
Requirement already satisfied: urllib3 in /usr/lib/python2.7/dist-packages (from selenium>=3.141.0->-r requirements.txt (line 2)) (1.24.1)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from user-agent>=0.1.9->-r requirements.txt (line 5)) (1.12.0)
root@kali:~/QRLJacking/QRLJacker# python3 QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/root/QRLJacking/QRLJacker/core/utils.py", line 5, in <module>
    from terminaltables import AsciiTable as table
ModuleNotFoundError: No module named 'terminaltables'
root@kali:~/QRLJacking/QRLJacker#
