### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by elieelias** [OWASP/QRLJacking#39]
ALL the youtube videos and online tutorials use old versions. How can i learn with the new version

**Comment by D4Vinci** [comment]
There would be a video tutorial in the next few days and maybe today

**Comment by elieelias** [comment]
okay thanks where should i check?

**Comment by D4Vinci** [comment]
I will update the repo documentation once finished and tell you here

**Comment by elieelias** [comment]
okay thanks a lot!
