### ISSUE TITLE
Unit-Tests for QRLJacker.py

### ISSUE THREAD

**Issue by ShawkyZ** [OWASP/QRLJacking#4]
The Script QRLJacker.py needs to be refactored and tested.

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!
