### ISSUE TITLE
Whatsapp QRLJacking not working 

### ISSUE THREAD

**Issue by MrDaniell** [OWASP/QRLJacking#41]
Hi I’m new in this site and I have a problem with qrljacking !!!

I installed qrljacking in kali linux 2018.4 but I have observed if I haven’t a qrl-framework for lounch the qrljacking mode!!!

When I type:     Python QRLJacking.py 
It don’t open nothing and give me SYNTAX ERROR

In kali Linux I have Python 2.7 

Where is the problems , please help me!!!!

**Comment by manan2501** [comment]
I think you using python 3 can solve your problem.

`pip3 install -r requirements.txt`
`python3 QrlJacking.py`

**Comment by AlainChaaya** [comment]
You should probably change the default python version from 2.7 to 3.7.
You can do that following the instructions from that link: https://unix.stackexchange.com/questions/410579/change-the-python3-default-version-in-ubuntu

**Comment by MrDaniell** [comment]
I tried it too but it doesn't work!  I tried write pip3 install -r requirements.txt but nothing!!!

**Comment by AlainChaaya** [comment]
I had the exact same issue did the same thing u did and it didn’t work. But idk why when i changed the default version using the link i commented above it worked so try this way before the pip3 install requirements

**Comment by MrDaniell** [comment]
ah OK so you say that it could be solved simply by installing Python 3?

**Comment by AlainChaaya** [comment]
Its pre-installed in kali you just need yo chande the default version to 3.7 before running the command: pip3 install -r requirements.txt

First type:

sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 1
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.7 2

Then type:
sudo update-alternatives --config python

This should fix the issue

**Comment by D4Vinci** [comment]
As said, yes it's version problem and I said that too in the instructions. The framework works with version 3.7 only.
Also, I just made a tutorial for installing and using the framework, check it out:
https://www.youtube.com/watch?v=sYtH5-K2JZc

**Comment by D4Vinci** [comment]
and thanks guys for the help 😄

**Comment by AlainChaaya** [comment]
Thanks for yours! 😄

**Comment by Michaenabil** [comment]
KeyError= "whatsapp" , any help with that ?!

**Comment by pervez1216** [comment]
I have installed python 3.7 
But qrljacking is not showing qrljacking-framework to me what to do

**Comment by YoAkky** [comment]
Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/QRLJacking/QRLJacker/core/browser.py", line 150, in serve_module
    self.browsers[module_name]["host"] = "http://"+host
KeyError: 'whatsapp'

**Comment by D4Vinci** [comment]
For KeyError issues see this pinned issue #37 

@pervez1216 see our install instructions, not an old youtube video!

**Comment by mende237** [comment]
I had the same problem as you, I solved it by following the instructions of this tutorial 
[https://www.youtube.com/watch?v=YRESw2ppQz8](url)

**Comment by aoc99** [comment]
__init__() should return None, not 'dict' when command run

**Comment by unexpectedbro** [comment]
I am trying to use it in wsl1 and I cant have wsl2.Can anyone tell me how to remove the cant open firefox problem and I tried it as localhost and to access via local ip adress and I also fix the selenium prble by usng the correct version.
