### ISSUE TITLE
QR-code not loading 

### ISSUE THREAD

**Issue by mohamedshaker9** [OWASP/QRLJacking#42]
the phishing page loading but QRcode not loading on target firefox

**Comment by D4Vinci** [comment]
Can you give me more details on what's the problem?
Does it stay after the new version I just released?

**Comment by mohamedshaker9** [comment]
after the new update it doesn't work 
![Capture](https://user-images.githubusercontent.com/34813615/55993380-3df4db00-5caf-11e9-98f6-3c5f42067f70.PNG)

**Comment by D4Vinci** [comment]
> after the new update it doesn't work
> ![Capture](https://user-images.githubusercontent.com/34813615/55993380-3df4db00-5caf-11e9-98f6-3c5f42067f70.PNG)

type debug then run and show me the output

**Comment by mohamedshaker9** [comment]
ok it's worked now but when i try to scan it from the phishing page whattsapp alert me to scan from wattsapp web and doesn;t open

**Comment by mohamedshaker9** [comment]
![Screenshot_20190411-232854](https://user-images.githubusercontent.com/34813615/55994441-fb80cd80-5cb1-11e9-9da0-19c7113243df.png)

**Comment by D4Vinci** [comment]
don't zoom the page before scanning

**Comment by mohamedshaker9** [comment]
OK thank  You it work .

**Comment by billone11** [comment]
hi i have a problemi with  the qrcode the phishing page loading but QRcode not loading how can i solve that

**Comment by billone11** [comment]
in linux 2022.3

**Comment by cariappats** [comment]
`<odule(grabber/whatsapp) > set port 4446
[+] port => 4446

<odule(grabber/whatsapp) > debug run
[+] Debug mode enabled!

<odule(grabber/whatsapp) > run
[+] Using the default useragent
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]                                                            
[+] Initializing webserver... [whatsapp]

<odule(grabber/whatsapp) > Exception in thread Webserver manager thread:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/browser.py", line 170, in serve_module
    webserver.start_serving(host)
  File "/home/kali/Downloads/QRLJacking/QRLJacker/core/module_utils.py", line 32, in start_serving
    self.httpd = ReusableTCPServer( (host, self.port), MyHandler)
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
`

**Comment by cariappats** [comment]
Qr code is not generating

**Comment by hak98** [comment]
Did this ever get solved?

**Comment by FiregGit** [comment]
> Did this ever get solved?

i don't think so!
i have the same problem.

**Comment by 0YunusHasan** [comment]
hi in the problem where the qr code is not generating the problem is the source of the qr code in the html is tmp.png but there is no temp.png in the directory. the tmp.png file is missing in the newer updates... if someone has the tmp.png file please give it

**Comment by dileep-2002** [comment]
> hi in the problem where the qr code is not generating the problem is the source of the qr code in the html is tmp.png but there is no temp.png in the directory. the tmp.png file is missing in the newer updates... if someone has the tmp.png file please give it

yes you are right even iam also facing the same problem here. is there any other solution not like importing old version png image
