### ISSUE TITLE
python QrlJacker.py command gives error and hence QRLJacker doesn't runs !!! 

### ISSUE THREAD

**Issue by silentBlakezz** [OWASP/QRLJacking#45]

**Comment by silentBlakezz** [comment]
root@kali:~/QRLJacking/QRLJacker# python QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax
root@kali:~/QRLJacking/QRLJacker#

**Comment by silentBlakezz** [comment]
Give solution to rectify this problem.

**Comment by SplendidX** [comment]
Hello.
Make sure to use python3 and not python when executing the file. This means you must get pip3 and reinstall requirements.txt

Good luck, 
Splendid

**Comment by silentBlakezz** [comment]
Same happened after using python3 and pip3 is shown as an invalid command!
root@kali:~/Desktop/QRLJacking/QRLJacker# python3 QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Desktop/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
    from core import utils,db,module,Settings,browser
  File "/root/Desktop/QRLJacking/QRLJacker/core/utils.py", line 5, in <module>
    from terminaltables import AsciiTable as table
ModuleNotFoundError: No module named 'terminaltables'
root@kali:~/Desktop/QRLJacking/QRLJacker#

**Comment by D4Vinci** [comment]
Kindly read the installation instructions!

**Comment by zhavid05** [comment]
> То же самое произошло после использования python3 и pip3 отображается как недопустимая команда!
> 
> ```
> root@kali:~/Desktop/QRLJacking/QRLJacker# python3 QrlJacker.py 
> Traceback (most recent call last):
>   File "QrlJacker.py", line 4, in <module>
>     from core import Cli,utils,Settings,db
>   File "/root/Desktop/QRLJacking/QRLJacker/core/Cli.py", line 5, in <module>
>     from core import utils,db,module,Settings,browser
>   File "/root/Desktop/QRLJacking/QRLJacker/core/utils.py", line 5, in <module>
>     from terminaltables import AsciiTable as table
> ModuleNotFoundError: No module named 'terminaltables'
> root@kali:~/Desktop/QRLJacking/QRLJacker#
> ```

have you solved the problem?

**Comment by zhavid05** [comment]
have you solved the problem?

**Comment by zhavid05** [comment]
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax

**Comment by zhavid05** [comment]
help please

**Comment by silentBlakezz** [comment]
Yeah I solved the issue. Make sure python 3 is installed in your pc,  then run the command : sudo apt-get install python3-pip
Then install the requirements and replace pip with pip3 there. Then run the program with python3 it will run.

**Comment by aabatis** [comment]
same issue it didn't work
