### ISSUE TITLE
Can't launch QrlJacker.py

### ISSUE THREAD

**Issue by whothiss** [OWASP/QRLJacking#47]
root@kali:~/Desktop/app/QRLJacking/QRLJacker# python3 QrlJacker.py
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Desktop/app/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'

Can anyone help me please?

**Comment by ronitprajapati** [comment]
i have this problem

**Comment by ronitprajapati** [comment]
please give me a solution

**Comment by jeretc** [comment]
Look at the error output, you're missing "ModuleNotFoundError: No module named 'readline'.
install it with "pip3 install readline". Make sure you have python3 installed.

**Comment by mianumar** [comment]
> readline'.
> install it with "pip3 install readline". Make sure you have python3 installed.

I run this commond but same problem

**Comment by D4Vinci** [comment]
Here I have two things to say:
1. You installed the requirements using python 3 not python 3.7, so use `python3.7 -m pip` to install the requirements with python 3.7.
2. As you have multiple python versions, always use the python3.7 command, not python3 ( Of course after doing step 1)

**Comment by pavankumar-reddy** [comment]
i too have a problem.i cant open it

**Comment by jibin-p-thomas** [comment]
> root@kali:~/Desktop/app/QRLJacking/QRLJacker# python3 QrlJacker.py
> Traceback (most recent call last):
> File "QrlJacker.py", line 4, in
> from core import Cli,utils,Settings,db
> File "/root/Desktop/app/QRLJacking/QRLJacker/core/Cli.py", line 4, in
> import os,sys,time,random,traceback,json,argparse,readline
> ModuleNotFoundError: No module named 'readline'
> 
> Can anyone help me please?

i too have this problem? anyone please give a solution??

**Comment by Derick8** [comment]
Same problem!, did all the steps mentioned in this  chain

Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/mytools/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'

**Comment by harshil2105** [comment]
Same issue doesn't work
