### ISSUE TITLE
No modules

### ISSUE THREAD

**Issue by deadfishhackers** [OWASP/QRLJacking#49]
it only has whatsapp module, and the command `run` doesnt work

**Comment by Morituri-te-salutant** [comment]
I have the same problem. The command 'run' almost doesn't work everytime except several times.

**Comment by D4Vinci** [comment]
Can you give more details about the issue? what's the problem here!?

**Comment by Morituri-te-salutant** [comment]
![image](https://user-images.githubusercontent.com/4383751/59650783-dfba0c00-91b9-11e9-98a2-bca11da95e7a.png)
here

**Comment by Morituri-te-salutant** [comment]
![image](https://user-images.githubusercontent.com/4383751/59650842-1001aa80-91ba-11e9-8c8b-ad513330d430.png)

**Comment by D4Vinci** [comment]
okay try restarting the framework and closing any instance of firefox, just to make sure of the problem.
If the problem persists, activate debug mode and show me the output.

**Comment by Morituri-te-salutant** [comment]
> okay try restarting the framework and closing any instance of firefox, just to make sure of the problem.
> If the problem persists, activate debug mode and show me the output.

I'm sorry that I just suddenly understand why it failed. Because I'm in China, there is an amazing thing called GFW. When I used my VPN to run the code, it successed. =_= I'm sorry for wasting time of you.

**Comment by D4Vinci** [comment]
No problem :smile:
