### ISSUE TITLE
Improve our Wiki

### ISSUE THREAD

**Issue by ShawkyZ** [OWASP/QRLJacking#5]
If you're a good English speaker you can go through our Wiki and look for typos and grammar mistakes.

**Comment by arpit1997** [comment]
I will try to solve this issue and improve project's wiki

**Comment by recluse27** [comment]
I could help you!

**Comment by masetrax** [comment]
I can help also.

**Comment by BryceFury** [comment]
I've corrected as much spelling, grammar and punctuation as is possible without re-writing the wiki. Since it's not open for editing, I've attached the new files here.













[QRLJacking_wiki_corrections.zip](https://github.com/OWASP/QRLJacking/files/502136/QRLJacking_wiki_corrections.zip)

**Comment by KamalAwasthi** [comment]
I think I could help!

**Comment by KamalAwasthi** [comment]
I have edited some of the pages. But as wiki pages are not compared during pull request, I can not make a pull request. And I also doubt if wiki editing would be counted in as a commit in Hacktoberfest

**Comment by DeltaHeavy** [comment]
I'm on it as well

**Comment by DeltaHeavy** [comment]
Edits to "Abstraction" in https://github.com/DeltaHeavy/QRLJacking including the appropriate renaming to "Abstract" addressing #5
