### ISSUE TITLE
Cannot find( QrlJacking-Framework)

### ISSUE THREAD

**Issue by Nikyhack** [OWASP/QRLJacking#50]
`Hello 
I'm very new to kali linux I cloned QRljacking to Desktop ,but when I try to change the direction to (QrlJacking-Framework)  is dosent mention in the list ,If anyone know  how to manege this issue ,please help me

**Comment by dineshthenesh** [comment]
use 'QRLJacker' instead QrlJacking-Framework

**Comment by Nikyhack** [comment]
Thank you and really appreciate the reply .

Sent from Mail for Windows 10
