### ISSUE TITLE
Can't Launch QrlJacker.py

### ISSUE THREAD

**Issue by HMD97** [OWASP/QRLJacking#52]
root@kali:~/Desktop/QRLJacking/QRLJacker# python3 QrlJacker.py --help
[!] The framework is designed to work only on python 3.7 or above!
[!] You are using version 3.6.8

root@kali:~/Desktop/QRLJacking/QRLJacker# python3.7 -V
Python 3.7.3

root@kali:~/Desktop/QRLJacking/QRLJacker# python3.7 QrlJacker.py --help
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Desktop/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'

**Comment by D4Vinci** [comment]
Here I have two things to say:
1. You installed the requirements using python 3 not python 3.7, so use `python3.7 -m pip` to install the requirements with python 3.7.
2. As you have multiple python versions, always use the python3.7 command, not python3 ( Of course after doing step 1)

**Comment by HMD97** [comment]
I used "python3.7 -m pip" to install the requirements but I got an error

root@kali:~/Desktop/QRLJacking/QRLJacker# python3.7 -m pip install -r requirements.txt
/usr/local/bin/python3.7: No module named pip

can you help me with this please?

**Comment by D4Vinci** [comment]
yes install pip for python 3.7

**Comment by HMD97** [comment]
pip is already installed and I tried to reinstall it again, but it still didn't work.
I just removed python, and used "python3 -m pip" to install the requirements
python --> python2.7
python3 --> python3.7
It worked! THANKS

**Comment by Mani4048888** [comment]
I can't understand please help.
$python3 -m requirements.txt
/*Not worked , how to specifically install using python 3.7 requirements...give code plz*/

**Comment by Mani4048888** [comment]
I am using terms...always installing python 3.8

**Comment by Mani4048888** [comment]
I am using termux .
$python3 QrlJacker.py

Getting the error ...python 3.7 or above etc.

**Comment by Mani4048888** [comment]
> pip is already installed and I tried to reinstall it again, but it still didn't work.
> I just removed python, and used "python3 -m pip" to install the requirements
> python --> python2.7
> python3 --> python3.7
> It worked! THANKS

Hai I am using termux ...
Please give the full code ...this is for kali Linux I think so..
Do you have fix for termux
