### ISSUE TITLE
qrl jacking is not openning

### ISSUE THREAD

**Issue by prasannabalaji08** [OWASP/QRLJacking#53]
root@kali:~/QRLJacking/QRLJacker# python3 QrlJacker.py 
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 4, in <module>
    import os,sys,time,random,traceback,json,argparse,readline
ModuleNotFoundError: No module named 'readline'

**Comment by Morituri-te-salutant** [comment]
Run 'pip install readline' please. You don't have the module named 'readline'.

**Comment by D4Vinci** [comment]
You installed the requirements using python 3 not python 3.7, so use `python3.7 -m pip` to install the requirements with python 3.7

**Comment by Luigiannoso** [comment]
when I use `python3.7 -m pip install readline`, it give me an error: 
    _error:*command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-6l68a6cx/readline/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-wwz_6tyl/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-6l68a6cx/readline/_

**Comment by TomerGamerTV** [comment]
can you show the command on how to install it?

**Comment by praveenbutowski** [comment]
im trying to run qrljacker but it throws this error

ModuleNotFoundError: No module named 'user_agent'

**Comment by host2india** [comment]
> im trying to run qrljacker but it throws this error
> 
> ModuleNotFoundError: No module named 'user_agent'

Same error to me as well
