### ISSUE TITLE
Image wont load up! tried different browser!

### ISSUE THREAD

**Issue by an0nkyle** [OWASP/QRLJacking#55]
![Screenshot at 2019-08-01 14-05-13](https://user-images.githubusercontent.com/53571063/62299982-0370a300-b444-11e9-851b-efb30fb711e9.png)
![Screenshot at 2019-08-01 14-05-23](https://user-images.githubusercontent.com/53571063/62299985-05d2fd00-b444-11e9-8f31-bfa5ae782a93.png)
![Screenshot at 2019-08-01 14-06-06](https://user-images.githubusercontent.com/53571063/62299990-079cc080-b444-11e9-8595-9f124c5be013.png)

**Comment by D4Vinci** [comment]
This could be because you changed something in the used folders try reinstalling it and use with no customizations.
Reopen this issue if the problem persists with more details!
