### ISSUE TITLE
useragent badly handled

### ISSUE THREAD

**Issue by Wh1teR4bb1t** [OWASP/QRLJacking#56]
Hi.

Just experienced a weird behavior with QrlJacker.

**Observed result** : when running the "run" command with some custom useragents, QrlJacker get sessions repeatedly without any real triggering. When running sessions on firefox, we just get web.whatsapp.com home page.

```
QrlJacker Module(grabber/whatsapp) > run
[+] Using useragent Mozilla/5.0 (Android 6.0; Mobile; rv:61.0) Gecko/61.0 Firefox/61.0
[+] Running a thread to keep the QR image  [whatsapp]
[+] Waiting for sessions on whatsapp
[+] Running a thread to detect Idle once it happens then click the QR reload button [whatsapp]
[+] Initializing webserver... [whatsapp]

[+] Got session on whatsapp module
[+] Session saved successfully

QrlJacker Module(grabber/whatsapp) > 
[+] Got session on whatsapp module
[+] Session saved successfully

[+] Got session on whatsapp module
[+] Session saved successfully

[+] Got session on whatsapp module
[+] Session saved successfully

[+] Got session on whatsapp module
[+] Session saved successfully

[+] Got session on whatsapp module
[+] Session saved successfully

[+] Got session on whatsapp module
[+] Session saved successfully

[+] Got session on whatsapp module
[+] Session saved successfully

[+] Got session on whatsapp module
[+] Session saved successfully

[+] Got session on whatsapp module
[+] Session saved successfully

[+] Got session on whatsapp module
[+] Session saved successfully

[+] Got session on whatsapp module
[+] Session saved successfully
```

**Step to reproduce the bug** : set this custom useragent before running : Mozilla/5.0 (Android 6.0; Mobile; rv:61.0) Gecko/61.0 Firefox/61.0

```
QrlJacker > use grabber/whatsapp

QrlJacker Module(grabber/whatsapp) > set port 1337
[+] port => 1337

QrlJacker Module(grabber/whatsapp) > set useragent 'Mozilla/5.0 (Android 6.0; Mobile; rv:61.0) Gecko/61.0 Firefox/61.0'
[+] useragent => Mozilla/5.0 (Android 6.0; Mobile; rv:61.0) Gecko/61.0 Firefox/61.0

QrlJacker Module(grabber/whatsapp) > run
```

Note that this issue seems to be due only to some custom useragent. This useragent for instance don't cause any issue : Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0

**Comment by D4Vinci** [comment]
This is because the user-agent you set is a mobile user-agent which makes web.whatsapp.com see you as a mobile user and opens a mobile version of the website.
Now because Qrljacker can't find QR image in the page (Because it's the mobile site) it thinks that you got a session. See it's a simple issue 😄 
>Solution: don't use mobile user-agent as a custom user-agent for obvious reasons
