### ISSUE TITLE
Anyone can help me? (error while start QrlJacker.py)

### ISSUE THREAD

**Issue by Xample33** [OWASP/QRLJacking#58]
python QrlJacker.py
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax

**Comment by D4Vinci** [comment]
Qrljacker needs python 3.7 to work and you have a lower version.
