### ISSUE TITLE
Improve QRLJacking-Framework Readme

### ISSUE THREAD

**Issue by ShawkyZ** [OWASP/QRLJacking#6]
[QRLJacking-Framework Readme.md](https://github.com/OWASP/QRLJacking/blob/master/QrlJacking-Framework/Readme.md)
Check for typos and grammar mistakes. 
Also try to see if the Getting-Started steps are clear enough.

**Comment by juliawong** [comment]
I'd like to work on this issue :smile:

**Comment by SymbianSyMoh** [comment]
We are working on a whole new version of QRLJacker, A multi-session framework full of features as a rewrite of the old #QRLJacker framework to hijack multiple accounts of several services that uses QR Code as a way of authentication, including WhatsApp, WeChat and many more. Stay tuned!
