### ISSUE TITLE
Syntax error when running.

### ISSUE THREAD

**Issue by quantumcore** [OWASP/QRLJacking#62]
Cloning the latest version. This is what I get when I run.
```bash
python3 QrlJacker.py --help
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/home/fahad/Documents/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax
```

**Comment by MrCrow32** [comment]
Hi, i have same problem

**Comment by TomerGamerTV** [comment]
same problem pls help (im on kali)

**Comment by D4Vinci** [comment]
You're not using Python 3.7 as said in the instructions so you get a syntax error in this line because of this is version 3.7 specific feature. See this pinned issue #47

**Comment by telugutech07** [comment]
> You're not using Python 3.7 as said in the instructions so you get a syntax error in this line because of this is version 3.7 specific feature. See this pinned issue #47

Bro same issue after that it's say
Modulenotfounderror:No Module named 'readline'
