### ISSUE TITLE
cant run QRLJacking on Kali Linux

### ISSUE THREAD

**Issue by TomerGamerTV** [OWASP/QRLJacking#64]
![image](https://user-images.githubusercontent.com/44266242/67105061-c14c3780-f1d0-11e9-8248-cadccd557947.png)
idk how to fix it pls help and yes i installed readline dont say it it dont work

**Comment by FabxBs** [comment]
![Immagine](https://user-images.githubusercontent.com/30447649/67125176-7b08cf80-f1f4-11e9-9e97-ce8305e31e0b.png)
everything done as the guide says, but i still get tables error.

**Comment by D4Vinci** [comment]
You have multiple Python versions installed, you install it with a version and run with another.
See this pinned issue #53
