### ISSUE TITLE
QR code not work

### ISSUE THREAD

**Issue by StarLabsUA** [OWASP/QRLJacking#66]
Hi, the code scans, but nothing happens, what could be the problem?
Recognizes just like text

**Comment by StarLabsUA** [comment]
The second problem:
s10 + cannot scan code due to handset in the middle

**Comment by D4Vinci** [comment]
Is the problem still persists?

**Comment by Mamugian** [comment]
@D4Vinci does it work for you? I will test it out later

**Comment by jepunband** [comment]
No qrcode.

![Screenshot at 2019-12-09 15-31-46](https://user-images.githubusercontent.com/46950575/70416138-4cdb9980-1a99-11ea-8426-e55dbaf8be1a.png)

**Comment by D4Vinci** [comment]
what user agent you set in the module options?

**Comment by Anirudh533** [comment]
I'm not getting the qr code on 0.0.0.0:1337. Image is not getting displayed. It says  
![Screenshot at 2020-01-25 21-29-55](https://user-images.githubusercontent.com/42970949/73123975-b9641680-3fbb-11ea-8e1f-45dab3b6c682.png)
![Screenshot at 2020-01-25 21-30-46](https://user-images.githubusercontent.com/42970949/73123976-bec16100-3fbb-11ea-8f1c-eb0aae0808f7.png)
Please help me to solve it!! Thank you in advance sir.

**Comment by Anirudh533** [comment]
![Screenshot at 2020-01-25 21-51-35](https://user-images.githubusercontent.com/42970949/73124083-05fc2180-3fbd-11ea-92b9-dad84d0a1258.png)
This error is being showed!

**Comment by D4Vinci** [comment]
yes, this the problem of the user agent used as I said!
If Whatsapp thinks you are a phone, it will ask you to install Whatsapp without displaying QR code for sure!!

**Comment by Anirudh533** [comment]
How to make this work?

**Comment by devilblackeye** [comment]
![Image](https://github.com/user-attachments/assets/7fb1b9f1-c1d3-4aea-9da1-62aa660ba7c6)

**Comment by devilblackeye** [comment]
Please help me to solve it!!
