### ISSUE TITLE
How to resolve KeyError: whatsapp QRLJacking

### ISSUE THREAD

**Issue by Taylorcmd** [OWASP/QRLJacking#70]
Hello! I had a problem in QRLJacking where it shows this Exception in thread Webserver manager thread: Traceback (most recent last call): File /usr/Lib/python3.7/threading.py ", line 926, in bootstrap_inner self.run () File" /usr/lib/python3.7/threading.py ", line 870, in run self._target (self._args, self._kaargs) File /root/ORLJacking/QRLJacker/core/browser.py", line 150, in serve_module self.browsers [module_name [host "] -" http: // "host KeyError: 'whatsapp' How to Solve?

**Comment by D4Vinci** [comment]
See #37
