### ISSUE TITLE
Can't launch QRLJacker

### ISSUE THREAD

**Issue by Spider8511** [OWASP/QRLJacking#72]
Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/root/Desktop/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^

**Comment by blaisy** [comment]
idem we have to adjust the code, i think, in this 2 / 3 days i will go to working on it......

**Comment by D4Vinci** [comment]
you are running the framework with python version 2, not 3!  👀
