### ISSUE TITLE
support python3.8 

### ISSUE THREAD

**Issue by whitehattamil** [OWASP/QRLJacking#80]
Hi sir
QRLJacker only supports python3.7
But python has upgraded to python 3.8
Please
Help
Me

**Comment by Mani4048888** [comment]
Same issue here please help..
I am using termux...also tried uninstalling and installing python , each time installs 3.8

All fixes in web and youtube are regarding KALI LINUX
please give an solution in termux

**Comment by varunkhumar** [comment]
pls anyone say any solution pls

**Comment by OmarMerghany** [comment]
@whitehattamil , @Mani4048888, @varunkhumar  I suggest for a temporary solution you can enforce python 3.7 version to be downloaded as in this [tutorial](https://linuxize.com/post/how-to-install-python-3-7-on-ubuntu-18-04/).
- You can also use python Virtualenv to install python 3.7 alongside your current installation

**Comment by melbadry9** [comment]
Latest commit fixed this issue
