### ISSUE TITLE
Followed all the inscructions but still not working. 

### ISSUE THREAD

**Issue by KedarJoshi11** [OWASP/QRLJacking#88]
Hi!

Here's what I did. 
1. Cloned the repo.
2. Installed latest geckodriver, followed all the instructions. 
3. Installed the requirements. 
4. Started the framework. 

However, it gives me the following response when I try to run it. The link to that image. 

Any help would be greatly appreciated. Thanks again for this!

![Error](https://user-images.githubusercontent.com/43803843/78469631-afd7f700-7740-11ea-894d-81e6c99be387.jpg)

**Comment by Mafufasi** [comment]
I too stuck herw

**Comment by RUGMJ7443** [comment]
+1

**Comment by anoopk654** [comment]
me too
