### ISSUE TITLE
Syntax Error in line 288

### ISSUE THREAD

**Issue by Florian-Mahlberg** [OWASP/QRLJacking#91]
Hello, when I started QrlJacker on Kali Linux (python QrlJacker.py) there came this error:

Traceback (most recent call last):
  File "QrlJacker.py", line 4, in <module>
    from core import Cli,utils,Settings,db
  File "/home/florian/Schreibtisch/QRLJacking/QRLJacker/core/Cli.py", line 288
    status(f"Starting interaction with ({cmd.i})...")
                                                   ^
SyntaxError: invalid syntax

**Comment by mmateen** [comment]
same problem

**Comment by hamzasaeed2029** [comment]
same problem :(

**Comment by hamzasaeed2029** [comment]
> Hello, when I started QrlJacker on Kali Linux (python QrlJacker.py) there came this error:
> 
> Traceback (most recent call last):
> File "QrlJacker.py", line 4, in
> from core import Cli,utils,Settings,db
> File "/home/florian/Schreibtisch/QRLJacking/QRLJacker/core/Cli.py", line 288
> status(f"Starting interaction with ({cmd.i})...")
> ^
> SyntaxError: invalid syntax

The framework is designed to work only on python 3.7 or above!

**Comment by hamzasaeed2029** [comment]
> same problem

The framework is designed to work only on python 3.7 or above!

**Comment by hamzasaeed2029** [comment]
Please update your python versions to 3.7 or above.

**Comment by hamzasaeed2029** [comment]
UPDATE:

**Comment by melbadry9** [comment]
@Florian-Mahlberg, We currently support Python 3.7  `python3 QrlJacker.py`
