### ISSUE TITLE
WhatsApp Web logged device

### ISSUE THREAD

**Issue by MetBorman** [OWASP/QRLJacking#93]
https://github.com/OWASP/QRLJacking/blob/master/blob/images/WhatsappSentBack.JPG

Hello everybody. Is it possible to hide a session on a smartphone in the whatsapp application (as in the screenshot). There is a notification about the use of the web session.

**Comment by pretech86** [comment]
@MetBorman very good idea , I appreciate you

**Comment by melbadry9** [comment]
This is not possible.
