### ISSUE TITLE
run is not recognized as an internal command

### ISSUE THREAD

**Issue by praveenbutowski** [OWASP/QRLJacking#99]
![Screenshot_2020-05-23-18-49-00-07_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/31473228/82731747-a0c7fb00-9d26-11ea-8887-3d2214aeb15b.png)

im getting this "run is not recognized as an internal command" in my both kali and termux

**Comment by DarkShade94649** [comment]
I Am also having the same issue Check this (I've also enabled debug mode)but i don't know what the issue is the core/module.py doesn't seems to be written wrong all the syntax is correct please email me if you get any solutions > darkshade94649@pm.me

**Comment by RUGMJ7443** [comment]
did you ever find the fix? im getting the same issue

**Comment by RUGMJ7443** [comment]
found the fix to this you need to install firefox and geckodriver

**Comment by melbadry9** [comment]
Can you still reproduce this issue?

**Comment by melbadry9** [comment]
Missing information.

**Comment by dr1408** [comment]
Anyone managed to make it work on termux I have both geckodriver and firefox installed but it gives me the run command not recognized
